# Generated by Django 3.0.6 on 2020-09-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first', models.CharField(max_length=20)),
                ('student_last', models.CharField(max_length=20)),
                ('teacher_first', models.CharField(max_length=20)),
                ('teacher_last', models.CharField(max_length=20)),
                ('schoolname', models.CharField(max_length=100)),
                ('confusion', models.IntegerField()),
                ('happy', models.IntegerField(default=0)),
                ('sad', models.IntegerField(default=0)),
                ('disgusted', models.IntegerField(default=0)),
                ('surprised', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('fear', models.IntegerField(default=0)),
                ('calm', models.IntegerField(default=0)),
                ('session', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=41)),
            ],
        ),
    ]
