# Generated by Django 3.0.6 on 2020-09-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='school_name',
            field=models.CharField(default='idk', max_length=100),
        ),
    ]
