# Generated by Django 3.0.6 on 2020-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_teachers_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first', models.CharField(max_length=20)),
                ('student_last', models.CharField(max_length=20)),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
