# Generated by Django 3.0.6 on 2020-09-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20200919_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=41)),
                ('school_name', models.CharField(max_length=100)),
                ('confusion', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('happy', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('sad', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('surprised', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('session', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='calm',
        ),
        migrations.RemoveField(
            model_name='school',
            name='disgusted',
        ),
        migrations.RemoveField(
            model_name='school',
            name='fear',
        ),
        migrations.RemoveField(
            model_name='school',
            name='unknown',
        ),
        migrations.AddField(
            model_name='frame',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachers',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
    ]
