# Generated by Django 3.0.6 on 2020-09-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20200919_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionQueries1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=41)),
                ('confusion', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('happy', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('sad', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('surprised', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='frame',
            name='student_first',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='student_last',
        ),
        migrations.AddField(
            model_name='frame',
            name='confusion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='student_name',
            field=models.CharField(default=None, max_length=41),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='surprised',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='teacher_name',
            field=models.CharField(default=None, max_length=41),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='confusion',
            field=models.IntegerField(default=0),
        ),
    ]
