# Generated by Django 3.0.6 on 2020-09-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20200919_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.CharField(max_length=1000000),
        ),
    ]
