# Generated by Django 3.0.6 on 2020-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20200920_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='schoolname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_first',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_last',
            field=models.CharField(default='', max_length=20),
        ),
    ]
