# Generated by Django 3.0.6 on 2020-09-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20200920_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='confusion',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='frame',
            name='happy',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='frame',
            name='sad',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='frame',
            name='surprised',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
